package Laporan;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import Dashboard.Dashboard;
import Penjualan.*;
import Film.*;
import Pelanggan.*;
import Users.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Koneksi.config;
import GlobalVariable.UserLoginVariable;
import java.text.SimpleDateFormat;

import java.util.Date;

/**
 *
 * @author Lenovo
 */
public class LaporanPenjualan extends javax.swing.JFrame {

    public UserLoginVariable userLoginData = new UserLoginVariable();
    public String sql;
    public Connection conn;
    public Statement stat;
    public ResultSet res;
    public String kategori;

    /**
     * Creates new form Users
     */
    public LaporanPenjualan() {
        initComponents();
        config konfigurasi = new config();
        konfigurasi.config();
        conn = konfigurasi.conn;
        stat = konfigurasi.stm;
        kategori = "id_penjualan";
        load_table();
    }

    public void load_table() {
        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("ID");
        table.addColumn("No Transkasi");
        table.addColumn("Judul Film");
        table.addColumn("Pelanggan");
        table.addColumn("User");
        table.addColumn("Harga Satuan");
        table.addColumn("Harga Total");
        table.addColumn("Jumlah");
        table.addColumn("Diskon");
        table.addColumn("Tanggal");
        try {
            sql = "SELECT tbl_penjualan.id_penjualan AS id_penjualan, tbl_penjualan.no_transaksi AS no_transaksi,tbl_film.judul AS judul_film, "
                    + "tbl_pelanggan.nama AS nama_pelanggan, tbl_users.nama AS nama_user, tbl_penjualan.harga_satuan AS harga_satuan, tbl_penjualan.harga_total AS harga_total,"
                    + "tbl_penjualan.jumlah AS jumlah, tbl_penjualan.diskon AS diskon, tbl_penjualan.tanggal AS tanggal "
                    + "FROM tbl_penjualan "
                    + "INNER JOIN tbl_film ON tbl_penjualan.id_film = tbl_film.id_film "
                    + "INNER JOIN tbl_pelanggan ON tbl_penjualan.id_pelanggan = tbl_pelanggan.id_pelanggan "
                    + "INNER JOIN tbl_users ON tbl_penjualan.id_user = tbl_users.id_user "
                    + "ORDER BY tbl_penjualan.id_penjualan ASC";
            res = stat.executeQuery(sql);
            while (res.next()) {
                table.addRow(new Object[]{
                    res.getString("id_penjualan"),
                    res.getString("no_transaksi"),
                    res.getString("judul_film"),
                    res.getString("nama_pelanggan"),
                    res.getString("nama_user"),
                    res.getString("harga_satuan"),
                    res.getString("harga_total"),
                    res.getString("jumlah"),
                    res.getString("diskon"),
                    res.getString("tanggal"),});
            }
            tabelFilm.setModel(table);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "fail get data " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelFilm = new javax.swing.JTable();
        cbKategori = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCari = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 204, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Laporan Penjualan");

        btnKeluar.setBackground(new java.awt.Color(255, 51, 51));
        btnKeluar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnKeluar.setForeground(new java.awt.Color(255, 255, 255));
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKeluar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelFilm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelFilm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabelFilm.setEnabled(false);
        jScrollPane1.setViewportView(tabelFilm);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1077, 380));

        cbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "No Transaksi", "User", "Film" }));
        cbKategori.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbKategoriItemStateChanged(evt);
            }
        });
        cbKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKategoriActionPerformed(evt);
            }
        });
        jPanel1.add(cbKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(928, 39, 159, -1));

        jLabel2.setText("Pencarian Bedasarkan");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 42, -1, -1));

        jLabel3.setText("Search");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 42, -1, -1));

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        jPanel1.add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 38, -1, -1));

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariKeyPressed(evt);
            }
        });
        jPanel1.add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 39, 227, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        switch (txtKae)
    }//GEN-LAST:event_formWindowOpened

    private void cbKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbKategoriActionPerformed

    private void cbKategoriItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbKategoriItemStateChanged
        switch (cbKategori.getSelectedIndex()) {
            case 0:
                kategori = "id_penjualan";
                break;
            case 1:
                kategori = "no_transaksi";
                break;
            case 3:
                kategori = "tbl_users.nama";
                txtCari.setVisible(true);
                break;
            case 4:
                kategori = "tbl_film.judul";
                txtCari.setVisible(true);
                break;
        }
    }//GEN-LAST:event_cbKategoriItemStateChanged

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        String date = "13 Oct 2016";

//        SimpleDateFormat d = new SimpleDateFormat("yyyy-MM-dd");
//        String tanggal = d.format(new Date());

        if (txtCari.getText().equals("")) {
            load_table();
        } else {
                DefaultTableModel table = new DefaultTableModel();
                table.addColumn("ID");
                table.addColumn("No Transkasi");
                table.addColumn("Judul Film");
                table.addColumn("Pelanggan");
                table.addColumn("User");
                table.addColumn("Harga Satuan");
                table.addColumn("Harga Total");
                table.addColumn("Jumlah");
                table.addColumn("Diskon");
                table.addColumn("Tanggal");
                try {
                    sql = "SELECT tbl_penjualan.id_penjualan AS id_penjualan, tbl_penjualan.no_transaksi AS no_transaksi,tbl_film.judul AS judul_film, "
                            + "tbl_pelanggan.nama AS nama_pelanggan, tbl_users.nama AS nama_user, tbl_penjualan.harga_satuan AS harga_satuan, tbl_penjualan.harga_total AS harga_total,"
                            + "tbl_penjualan.jumlah AS jumlah, tbl_penjualan.diskon AS diskon, tbl_penjualan.tanggal AS tanggal "
                            + "FROM tbl_penjualan "
                            + "INNER JOIN tbl_film ON tbl_penjualan.id_film = tbl_film.id_film "
                            + "INNER JOIN tbl_pelanggan ON tbl_penjualan.id_pelanggan = tbl_pelanggan.id_pelanggan "
                            + "INNER JOIN tbl_users ON tbl_penjualan.id_user = tbl_users.id_user "
                            + "WHERE " + kategori + " LIKE '%" + txtCari.getText() + "%'"
                            + "ORDER BY tbl_penjualan.id_penjualan ASC";
                    res = stat.executeQuery(sql);
                    while (res.next()) {
                        table.addRow(new Object[]{
                            res.getString("id_penjualan"),
                            res.getString("no_transaksi"),
                            res.getString("judul_film"),
                            res.getString("nama_pelanggan"),
                            res.getString("nama_user"),
                            res.getString("harga_satuan"),
                            res.getString("harga_total"),
                            res.getString("jumlah"),
                            res.getString("diskon"),
                            res.getString("tanggal"),});
                    }
                    tabelFilm.setModel(table);
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "fail get data " + e.getMessage());
                }
            
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void txtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyPressed
//        if (txtCari.getText().equals("")) {
//            load_table();
//        } else {
//            DefaultTableModel table = new DefaultTableModel();
//            table.addColumn("ID");
//            table.addColumn("No Transkasi");
//            table.addColumn("Judul Film");
//            table.addColumn("Pelanggan");
//            table.addColumn("User");
//            table.addColumn("Harga Satuan");
//            table.addColumn("Harga Total");
//            table.addColumn("Jumlah");
//            table.addColumn("Diskon");
//            table.addColumn("Tanggal");
//            try {
//                sql = "SELECT tbl_penjualan.id_penjualan AS id_penjualan, tbl_penjualan.no_transaksi AS no_transaksi,tbl_film.judul AS judul_film, "
//                        + "tbl_pelanggan.nama AS nama_pelanggan, tbl_users.nama AS nama_user, tbl_penjualan.harga_satuan AS harga_satuan, tbl_penjualan.harga_total AS harga_total,"
//                        + "tbl_penjualan.jumlah AS jumlah, tbl_penjualan.diskon AS diskon, tbl_penjualan.tanggal AS tanggal "
//                        + "FROM tbl_penjualan "
//                        + "INNER JOIN tbl_film ON tbl_penjualan.id_film = tbl_film.id_film "
//                        + "INNER JOIN tbl_pelanggan ON tbl_penjualan.id_pelanggan = tbl_pelanggan.id_pelanggan "
//                        + "INNER JOIN tbl_users ON tbl_penjualan.id_user = tbl_users.id_user "
//                        + "WHERE " + kategori + " LIKE '%" + txtCari.getText() + "%'"
//                        + "ORDER BY tbl_penjualan.id_penjualan ASC";
//                res = stat.executeQuery(sql);
//                while (res.next()) {
//                    table.addRow(new Object[]{
//                        res.getString("id_penjualan"),
//                        res.getString("no_transaksi"),
//                        res.getString("judul_film"),
//                        res.getString("nama_pelanggan"),
//                        res.getString("nama_user"),
//                        res.getString("harga_satuan"),
//                        res.getString("harga_total"),
//                        res.getString("jumlah"),
//                        res.getString("diskon"),
//                        res.getString("tanggal"),});
//                }
//                tabelFilm.setModel(table);
//            } catch (SQLException e) {
//                JOptionPane.showMessageDialog(null, "fail get data " + e.getMessage());
//            }
//        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanPenjualan.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanPenjualan.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanPenjualan.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanPenjualan.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanPenjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JComboBox<String> cbKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelFilm;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
